# Copyright (c) 2024-2026 O.S. Systems Software LTDA.
# Copyright (c) 2024-2026 Freedom Veiculos Eletricos
# SPDX-License-Identifier: Apache-2.0

manifest:
  defaults:
    remote: ossystems

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: ossystems
      url-base: git@github.com:OSSystems
    - name: rodrigopex
      url-base: https://github.com/rodrigopex

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 5967ceb85f00055644eafbec3fce232cdb886531 # main
      import:
        path-prefix: deps
        path-allowlist:
          - modules/hal/cmsis_6
          - modules/hal/stm32
    - name: lua_zephyr
      remote: rodrigopex
      revision: 4413b369f44cb9a35b726ff5c8f37ad1df88bce3 # main
      path: deps/modules/lib/lua_zephyr
      submodules: true

  self:
    import:
