# Copyright (c) 2024 O.S. Systems Software LTDA.
# Copyright (c) 2024 Freedom Veiculos Eletricos
# SPDX-License-Identifier: Apache-2.0

manifest:
  defaults:
    remote: ossystems

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: ossystems
      url-base: git@github.com:OSSystems

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
        path-prefix: deps
        path-allowlist:
          - modules/hal/cmsis
          - modules/hal/stm32

  self:
    import:
