/*
 * Copyright (c) 2026 O.S. Systems Software LTDA.
 * Copyright (c) 2026 Freedom Veiculos Eletricos
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Wire user Lua override files into the BT context.
 * Headers are generated by zephyrbt_add_lua_file() via
 * lua_zephyr's luaz_gen.py script.
 *
 * Loading order matters: diagnostics.lua first since
 * other files depend on manhattan().
 */

#include <zephyr/zephyrbt/zephyrbt.h>

#include "diagnostics_lua_script.h"
#include "navigation_lua_script.h"
#include "safety_lua_script.h"
#include "mission_lua_script.h"

static const char *const user_scripts[] = {
	diagnostics_lua_script,
	navigation_lua_script,
	safety_lua_script,
	mission_lua_script,
};

void zephyrbt_lua_user_init(struct zephyrbt_context *ctx)
{
	ctx->lua_user_scripts = user_scripts;
	ctx->lua_user_script_count = 4;
}
